### ISSUE TITLE
NDVR functionality for  DASH and HLS

### ISSUE THREAD

**Issue by 5centscdn** [kaltura/media-framework#179]
Is it possible to add DVR functionality for Dash and HLS?

I would like to use DASH and HLS packaging for a DVR-type service, where people can access anything streamed in the last 2 days. Is it possible to increase the HLS and Dash playlist length to enable NDVR functionality?

Hope to hear from you soon!

**Comment by erankor** [comment]
Yes -
1. nginx-live-module has support for storing the media in S3 (or compatible) bucket. You can see the relevant conf directives here - https://github.com/kaltura/media-framework/tree/master/nginx-live-module#s3-storage-directives.
2. nginx-live-module has support for "timelines", you can create a timeline with a duration of 2 days, that will keep track of all the segments. You can then create additional timelines by clipping the large timeline - use the create timeline API with the `source` property pointing to the large timeline, and the `start` / `end` parameters containing the timestamps of the "show".

It is technically possible to also use the large timeline to generate the index.m3u8/manifest.mpd, but if the timeline is very large, it may become too heavy for the player.

**Comment by 5centscdn** [comment]
Hello @erankor ,

Thank you for your response. I've successfully configured the first option (S3), but I'm uncertain about the second option. Is there any documentation available on how to set a "timeline" with a duration of 2 days? I've already checked the following link: https://github.com/kaltura/media-framework/blob/master/nginx-live-module/README.md, but I couldn't find the appropriate settings.

Could you please share the steps for creating a timeline with a duration of 2 days? Your assistance would be greatly appreciated.

**Comment by erankor** [comment]
There are several properties on the timeline object (https://github.com/kaltura/media-framework/blob/master/nginx-live-module/README.md#timeline-object) that define the limits of the timeline - `max_duration`, `max_segments`, `manifest_max_segments`, `manifest_max_duration`. 
The `segments` variants, put a limit on the number of segments in the timeline. The `duration` variants, put a limit on the total duration of the timeline in timescale units (90kHz by default). 
Internally, the timeline contains two lists of segments, one of them is used for building manifests (m3u8/mpd), and the other is used for validating segment requests. This is in order to have a few additional segments available for download, on top of what is returned in the manifest (as required by the HLS standard). This is the reason we have the `manifest` variants...
Anyway, if you want to create a timeline of 2 days, you can set both max_duration, and manifest_max_duration to 15552000000 (=48 * 3600 * 90000), and leave the two max_segments fields unset (=unlimited)
