### ISSUE TITLE
Support for FLAC?

### ISSUE THREAD

**Issue by Hadryan** [kaltura/media-framework#19]

**Comment by erankor** [comment]
Hi, I'm planning to add support for additional codecs soon. FLAC is very low priority from my side, but as far as I remember, it's also very low effort, so might as well add it too...
Out of curiosity :) since we have yet to write any sample configuration/documentation etc. was wondering whether you actually managed to try this project out? or you're asking this because FLAC is a prerequisite?

**Comment by erankor** [comment]
I checked about adding FLAC, and it seems there is no standard for embedding FLAC in MPEG-TS container. So I don't see how FLAC is going to be streamed to our system, we support only RTMP & MPEG-TS...

**Comment by Hadryan** [comment]
> ... was wondering whether you actually managed to try this project out? 

I saw your project codes and it seems very promising. I also used kaltura VOD on different productions. That would be great if this new project supports FLAC support because of extraordinary audio quality
